- name: Deploy Static Site
  hosts: all
  become: yes
  tasks:
    - name: Copy local tarball to server
      copy:
        src: ./static_site.tar.gz
        dest: /tmp/static_site.tar.gz

    - name: Create a directory for a static site
      file:
        path: /var/www/static_site
        state: directory
        mode: '0755'

    - name: Extract tarball on server
      unarchive:
        src: /tmp/static_site.tar.gz
        dest: /var/www/static_site
        remote_src: yes

    - name: Remove temp tarball
      file:
        path: /tmp/static_site.tar.gz
        state: absent
